elasticsearch:
  image: deviantony/elk-elasticsearch
  ports:
    - "9200:9200"
logstash:
  image: deviantony/elk-logstash
  stdin_open: true
#  tty: true
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana3:
  image: deviantony/elk-kibana:kibana3
  ports:
    - "7999:80"
  links:
    - elasticsearch
kibana4:
  image: deviantony/elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
